#Logging configurations
[LOGGING]
level="DEBUG"
[[LOGGING.logFileConfigs]]
logPath="./logs"
fileName="mailEngine"
maxAge=1
maxBackup=3
maxSize=10
compression=true
#DB configurations
[DB]
[[DB.mongoConfigs]]
uri="mongodb://localhost:27017"
timeout=60
database="mailtemplatedb"
user=""
password=""
authdb=""